name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release-moto-job:
    strategy:
      fail-fast: false
      matrix:
        include:
          - action-runner: arc-runner-set
            platform: linux/arm64
          - action-runner: ubuntu-latest
            platform: linux/amd64
    name: Release Moto
    env:
      VERSION: 0.0.0
    permissions:
      id-token: write
      contents: write
    runs-on: ${{ matrix.action-runner }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::489098123993:role/github-actions-assumable-role
        aws-region: us-east-1
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - id: build_and_push
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ matrix.platform }}
        push: true
        tags: public.ecr.aws/bluegroundltd/motoserver:latest
